export const LEVELS = ['100', '200', '300', '400', '500'];

export const GENDERS = ['Male', 'Female'];

export const COURSES = [
  'Accounting & Finance',
  'Agricultural Economics and Extension',
  'Animal Sciences',
  'Biochemistry',
  'Biology',
  'Biotechnology',
  'Business Administration',
  'Business Education',
  'Chemistry',
  'Computer Science',
  'Crop Sciences',
  'Criminology & Security Studies',
  'Economics',
  'Educational Management',
  'Energy studies',
  'English Language',
  'Fisheries and Agriculture',
  'Geology',
  'Health Education',
  'History & Diplomatic Studies',
  'Human kinetics',
  'Information Technology',
  'International Relations And Diplomacy',
  'Law',
  'Library and Information Science',
  'Mass Communication',
  'Mathematics',
  'Microbiology',
  'Peace And Development Studies',
  'Physics',
  'Public Administration',
  'Social Studies',
  'Statistics',
];
